(trace check-program
check-toplevel-forms
check-toplevel-form
check-definition
check-expressions
check-expression
check-time-expression
check-if-expression
check-and-expression
check-or-expression
check-cond-expression
check-cond-clauses
check-cond-clause
check-else-clause
check-case-expression
check-case-clauses
check-case-clause
check-quotations
check-let-expression
check-let-bindings
check-let-binding
check-letstar-expression
check-letstar-bindings
check-letstar-binding
check-letrec-expression
check-letrec-bindings
check-letrec-binding
check-begin-expression
check-unless-expression
check-quote-expression
check-quotation
check-lambda-abstraction
check-lambda-formals
check-application)